package com.global.language.web_content_translate.model.param.translation;

import java.io.Serializable;
import java.util.StringJoiner;

/**
 *   翻译表，用于存储网页内容的翻译信息
 *   表：translation
 *
 * @author lukenc
 * @date 2023年05月18日 10:46:52
 */
public class TranslationEditParam implements Serializable {

    private Integer id;

    /**
     *
     *  对应网页内容表的主键，表示所属的网页内容的ID
     *
     * 数据库字段： translation.content_id
     *
     * @author lukenc
     */
    private Integer contentId;

    /**
     *
     *  语言的ID，用于标识属于哪个语言
     *
     * 数据库字段： translation.language_id
     *
     * @author lukenc
     */
    private Integer languageId;

    /**
     *
     *  目标语言的标识符，如ISO语言代码
     *
     * 数据库字段： translation.language_code
     *
     * @author lukenc
     */
    private String languageCode;




    /**
     * 
     *  翻译后的文本内容
     *
     * 数据库字段： translation.translated_text
     *
     * @author lukenc
     */
    private String translatedText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translation
     *
     * @author lukenc
     */
    private static final long serialVersionUID = 1L;


    public Integer getContentId() {
        return contentId;
    }

    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    public Integer getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public String getTranslatedText() {
        return translatedText;
    }

    public void setTranslatedText(String translatedText) {
        this.translatedText = translatedText;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", TranslationEditParam.class.getSimpleName() + "[", "]")
                .add("id=" + id)
                .add("contentId=" + contentId)
                .add("languageId=" + languageId)
                .add("languageCode='" + languageCode + "'")
                .add("translatedText='" + translatedText + "'")
                .toString();
    }
}