package com.global.language.web_content_translate.model.enity;

import java.io.Serializable;
import java.util.Date;

/**
 *   语言表，用于存储支持的语言信息
 *   表：language
 *
 * @author lukenc
 * @date 2023年05月18日 10:46:16
 */
public class Language implements Serializable {
    /**
     * 
     *  语言的唯一标识符
     *
     * 数据库字段： language.id
     *
     * @author lukenc
     */
    private Integer id;

    /**
     * 
     *  语言名称，运维人员管理使用
     *
     * 数据库字段： language.name
     *
     * @author lukenc
     */
    private String name;

    /**
     * 
     *  ISO语言代码
     *
     * 数据库字段： language.iso_code
     *
     * @author lukenc
     */
    private String isoCode;

    /**
     * 
     *  语言的本地名称,用于展示给用户找到自己的语言
     *
     * 数据库字段： language.native_name
     *
     * @author lukenc
     */
    private String nativeName;

    /**
     * 
     *  创建人
     *
     * 数据库字段： language.created_by
     *
     * @author lukenc
     */
    private String createdBy;

    /**
     * 
     *  创建时间
     *
     * 数据库字段： language.created_at
     *
     * @author lukenc
     */
    private Date createdAt;

    /**
     * 
     *  最后修改人
     *
     * 数据库字段： language.modified_by
     *
     * @author lukenc
     */
    private String modifiedBy;

    /**
     * 
     *  最后修改时间
     *
     * 数据库字段： language.modified_at
     *
     * @author lukenc
     */
    private Date modifiedAt;

    /**
     *
     * 数据库字段： language.enable
     *
     * @author lukenc
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table language
     *
     * @author lukenc
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取language.id
     *
     * @return the value of language.id
     *
     * @author lukenc
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置language.id
     *
     * @param id the value for language.id
     *
     * @author lukenc
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取language.name
     *
     * @return the value of language.name
     *
     * @author lukenc
     */
    public String getName() {
        return name;
    }

    /**
     * 设置language.name
     *
     * @param name the value for language.name
     *
     * @author lukenc
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取language.iso_code
     *
     * @return the value of language.iso_code
     *
     * @author lukenc
     */
    public String getIsoCode() {
        return isoCode;
    }

    /**
     * 设置language.iso_code
     *
     * @param isoCode the value for language.iso_code
     *
     * @author lukenc
     */
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode == null ? null : isoCode.trim();
    }

    /**
     * 获取language.native_name
     *
     * @return the value of language.native_name
     *
     * @author lukenc
     */
    public String getNativeName() {
        return nativeName;
    }

    /**
     * 设置language.native_name
     *
     * @param nativeName the value for language.native_name
     *
     * @author lukenc
     */
    public void setNativeName(String nativeName) {
        this.nativeName = nativeName == null ? null : nativeName.trim();
    }

    /**
     * 获取language.created_by
     *
     * @return the value of language.created_by
     *
     * @author lukenc
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * 设置language.created_by
     *
     * @param createdBy the value for language.created_by
     *
     * @author lukenc
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * 获取language.created_at
     *
     * @return the value of language.created_at
     *
     * @author lukenc
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 设置language.created_at
     *
     * @param createdAt the value for language.created_at
     *
     * @author lukenc
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 获取language.modified_by
     *
     * @return the value of language.modified_by
     *
     * @author lukenc
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * 设置language.modified_by
     *
     * @param modifiedBy the value for language.modified_by
     *
     * @author lukenc
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * 获取language.modified_at
     *
     * @return the value of language.modified_at
     *
     * @author lukenc
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * 设置language.modified_at
     *
     * @param modifiedAt the value for language.modified_at
     *
     * @author lukenc
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * 获取language.enable
     *
     * @return the value of language.enable
     *
     * @author lukenc
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * 设置language.enable
     *
     * @param enable the value for language.enable
     *
     * @author lukenc
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * 
     * 转字符 
     * 
     * @return String
     *
     * @author lukenc
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", isoCode=").append(isoCode);
        sb.append(", nativeName=").append(nativeName);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", modifiedBy=").append(modifiedBy);
        sb.append(", modifiedAt=").append(modifiedAt);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


    public static Language create(String name, String isoCode, String nativeName){
        Language language= new Language();
        language.name=name;
        language.isoCode=isoCode;
        language.nativeName=nativeName;
        return language;
    }
}