package com.global.language.web_content_translate.model.param.webContent;

import java.io.Serializable;
import java.util.StringJoiner;

/**
 *   新建网页内容表的请求参数
 *
 * @author lukenc
 * @date 2023年05月18日 10:47:08
 */
public class WebContentAddParam implements Serializable {


    /**
     * 
     *  网页的URL
     *
     * 数据库字段： web_content.url
     *
     * @author lukenc
     */
    private String url;



    /**
     * 
     *  例如button，list
     *
     * 数据库字段： web_content.type
     *
     * @author lukenc
     */
    private String type;


    /**
     * 
     *  原始网页内容
     *
     * 数据库字段： web_content.original_content
     *
     * @author lukenc
     */
    private String originalContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_content
     *
     * @author lukenc
     */
    private static final long serialVersionUID = 1L;


    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOriginalContent() {
        return originalContent;
    }

    public void setOriginalContent(String originalContent) {
        this.originalContent = originalContent;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", WebContentAddParam.class.getSimpleName() + "[", "]")
                .add("url='" + url + "'")
                .add("type='" + type + "'")
                .add("originalContent='" + originalContent + "'")
                .toString();
    }
}